[package]
name = "mlogium"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [ "code","derive", "parse"]

[dependencies]
parse = { path = "parse" }
code = { path = "code" }
ariadne = "0.5.1"
